version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:user
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=nisum
      - SPRING_DATASOURCE_PASSWORD=nisum123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none